### PR TITLE
Resolved Error: Unable to access jarfile target/my-app 

### PR DESCRIPTION
**Pull request by saami97**
The error is resolved now.

image

image

### CODE REVIEW

**Comment by saami97** [comment]
This was in response to the issue https://github.com/jenkins-docs/simple-java-maven-app/issues/784

**Review by MarkEWaite — CHANGES_REQUESTED** [review]
We can't switch the agent type to `any` without breaking the tutorial for all users that do not have the correct version of maven and Java installed.

Please explain more details about the failure that you encountered so that we can identify the root cause of the failure.  Changing the agent type is not the correct solution.

**Review by saami97 — COMMENTED** [review]
I have reverted back the agent to docker. I am running jenkins on docker and maybe that caused the agent error, given below. 
However, when I changed it to any it got resolved. I believe it might be related to my jenkins setup

```
Started by user [admin](http://34.100.240.67:8080/user/admin)
Obtained jenkins/Jenkinsfile from git https://github.com/saami97/simple-java-maven-app.git
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 3: Invalid agent type "docker" specified. Must be one of [any, label, none] @ line 3, column 9.
           docker {
           ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1107)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:624)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:602)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:323)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:293)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox$Scope.parse(GroovySandbox.java:163)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:190)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:175)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:635)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:581)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:335)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
Finished: FAILURE
```

**Comment by saami97** [comment]
However, the that I reported in https://github.com/jenkins-docs/simple-java-maven-app/issues/784 still remained. That got resolved, only after I changed the regular expression in deliver.sh file.

**Comment by MarkEWaite** [comment]
Thanks for the pull request.  Apache Maven now provides a technique that will output the value of a property without any additional decoration.  I've submitted a pull request to apply that change:

* #800

**Pull request closed without merging**
